---
- name: Spinup Instance 
  hosts: localhost
  user: root
  become: yes
  become_method: sudo
  
  roles:
    - instance

- name: Install Tomcat & Deploy files
  hosts: ec2hosts
  gather_facts: False
  user: ec2-user
  become: yes
  become_method: sudo

  vars_files:
    - ./group_vars/variable
         
  roles:
    - selinux
    - tomcatinstall

